FORMAT: 1A

# Aplicação TEM Saúde

Documentação de referência da API REST para a implementação da aplicação mobile da Rede TEM.

## URL

A URL base da API depende do ambiente:

<dl>
<dt>Homologação</dt>
<dd>https://qa-api-app.temrede.com.br</dd>
<dt>Produção</dt>
<dd>https://api-app.temrede.com.br</dd>
</dl>

> O endereço de produção só funciona para IP previamente liberado.

## Lista de APIs

Segue a lista de APIs consumidas pela aplicação mobile:

- [API Login e Cadastro do Usuário](login.html)
- [API Agendamento de Consultas e Exames](scheduling.html)
- ...
