FORMAT: 1A

# API Sempre

API REST para integração com o sistema Sempre.

## URL

A URL base depende do ambiente:

<dl>
<dt>Homologação</dt>
<dd>https://qa-api-sempre.temrede.com.br</dd>
<dt>Produção</dt>
<dd>https://api-sempre.temrede.com.br</dd>
</dl>

> O endereço de produção só funciona para IP previamente liberado.

## Autenticação

Essa API exige autenticação usando o método OAuth 2.0.
As credenciais para obter o token devem ser solicitadas previamente.

# Group Endpoints

## Geração de Cartões [/api/sempre/cards/generate]

### POST

Solicita a geração de cartões de saúde da TEM ainda não associados a um cliente.

A entrada deve ser um JSON, informando a quantidade de cartões a ser gerada, o código do produto e a identificação da operação:

```json
{
    "quantity": "1",
    "onixCode": "<ONIX_CODE>",
    "insertUser": "<USUÁRIO>"
}
```

No retorno de sucesso, uma lista de cartões é retornada (exemplos abaixo).

_Códigos de erro:_

- `400`: para erros na requisição, como de sintaxe ou um código de produto inválido.
- `401`: para erros relativos à autenticação ou à autorização.

+ Request Gerar 1 cartão (application/json)
    + Headers

            Authorization: Bearer <TOKEN>

    + Attributes (object)
        + quantity: `1` (number) - Quantidade de cartões para gerar
        + onixCode: `<ONIX_CODE>` (string) - O código do produto em que os cartões serão gerados
        + insertUser: `<USUÁRIO>` (string) - Identificação de quem fez a operação

+ Response 201 (application/json)

    + Attributes (object)
        + status: `201` (number) - O mesmo código de resposta do HTTP
        + defaultMessage: `Criação de cartões` (string) - Descrição da resposta
        + body (array[Card])

+ Request Gerar 2 cartões (application/json)
    + Headers

            Authorization: Bearer <TOKEN>

    + Body

            {
                "quantity": 2,
                "onixCode": "<ONIX_CODE>",
                "insertUser": "<USUÁRIO>"
            }

+ Response 201 (application/json)

        {
            "status": 201,
            "defaultMessage": "Criação de cartões",
            "body": [
                {
                    "cardNumber": "1234567654321234",
                    "cvv": "321",
                    "way": "1",
                    "password": "874125",
                    "emitter": "755",
                    "product": "<ONIX_CODE>"
                },
                {
                    "cardNumber": "4687952416475856",
                    "cvv": "544",
                    "way": "1",
                    "password": "697453",
                    "emitter": "755",
                    "product": "<ONIX_CODE>"
                }
            ]
        }

## Carga de Cliente [/api/sempre/clients/load]

### POST

Faz a carga de um cliente a um cartão de saúde. O cartão pode ser um existente (o número do cartão deve ser passado) ou o cartão pode ser gerado na hora.

A entrada deve ser um JSON, informando os dados do cliente, com os seguintes campos:

| Campos               | Tipo   | Min. | Máx. | Obrigatório | Descrição                                                                                                                                                                                                                                                                                              |
| -------------------- | ------ | ---- | ---- | :---------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `currentUser`        | String | 1    | 128  | Sim         | Identificação de quem está fazendo a operação.                                                                                                                                                                                                                                                         |
| `action`             | Number | 1    | 1    | Sim         | Ação a ser efetuada: `1` (Adesão) e `4` (Suspensão).                                                                                                                                                                                                                                                   |
| `onixCode`           | Number | 4    | 4    | Sim         | Código do produto usado no cartão de saúde.                                                                                                                                                                                                                                                            |
| `cpfOrCnpj`          | Number | 11   | 11   | Sim         | Número de CPF do cliente.                                                                                                                                                                                                                                                                              |
| `name`               | String | 6    | 50   | Sim         | Nome completo do cliente.                                                                                                                                                                                                                                                                              |
| `shortName`          | String | 6    | 20   | Não         | Nome abreviado (usado no cartão).                                                                                                                                                                                                                                                                      |
| `birthdate`          | String | 10   | 10   | Sim         | Data de nascimento do cliente no formato yyyy-MM-dd.                                                                                                                                                                                                                                                   |
| `telephone`          | String | 11   | 11   | Sim         | Número de celular do cliente com DDD.                                                                                                                                                                                                                                                                  |
| `gender`             | String | 1    | 1    | Sim         | Gênero do cliente (`M`/`F`).                                                                                                                                                                                                                                                                           |
| `cardNumber`         | String | 14   | 16   | Não         | Número do cartão de saúde (obrigatório em alguns produtos).                                                                                                                                                                                                                                            |
| `majorCard`          | String | 14   | 16   | Não         | Número do cartão pai.                                                                                                                                                                                                                                                                                  |
| `externalIdentifier` | String | -    | 20   | Não         | Identificador externo usado para identificar o cartão e/ou cliente no sistema externo do parceiro.                                                                                                                                                                                                     |
| `email`              | String | -    | 200  | Não         | Um e-mail válido para contato com o cliente.                                                                                                                                                                                                                                                           |
| `address`            | String | -    | 40   | Não         | Endereço do cliente (logradouro)                                                                                                                                                                                                                                                                       |
| `number`             | String | -    | 6    | Não         | Endereço do cliente (número)                                                                                                                                                                                                                                                                           |
| `complement`         | String | -    | 20   | Não         | Endereço do cliente (complemento)                                                                                                                                                                                                                                                                      |
| `neighborhood`       | String | -    | 50   | Não         | Endereço do cliente (bairro)                                                                                                                                                                                                                                                                           |
| `city`               | String | -    | 50   | Não         | Endereço do cliente (cidade)                                                                                                                                                                                                                                                                           |
| `state`              | String | 2    | 2    | Não         | Endereço do cliente (UF)                                                                                                                                                                                                                                                                               |
| `postalCode`         | String | -    | 8    | Não         | Endereço do cliente (CEP) - somente números                                                                                                                                                                                                                                                            |
| `nationality`        | String | -    | 20   | Não         | Naturalidade do cliente.                                                                                                                                                                                                                                                                               |
| `rg`                 | String | -    | 50   | Não         | Número do documento do cliente.                                                                                                                                                                                                                                                                        |
| `documentType`       | Number | 1    | 1    | Não         | Tipo de documento: `1` (RG), `2` (PASSAPORTE), `3` (CTPS) ou `4` (CNH).                                                                                                                                                                                                                                |
| `race`               | Number | 1    | 1    | Não         | Etnia do cliente: `1` (Branca), `2` (Negra), `3` (Parda), `4` (Amarela), `5` (Indígena) ou `99` (sem informação).                                                                                                                                                                                      |
| `scholarity`         | Number | 1    | 1    | Não         | Escolaridade do cliente: `1` (Analfabeto), `2` (Alfabetizado), `3` (1o Grau Incompleto), `4` (1o Grau Completo), `5` (2o Grau Incompleto) `6` (2o Grau Completo), `7` (Superior Incompleto), `8` (Superior Completo), `9` (Especialização), `10` (Mestrado), `11` (Doutorado) ou `99` (sem informação) |
| `incomeClass`        | Number | 1    | 1    | Não         | Classe de rendimento: `1` (Até 1 salário mínimo), `2` (De 2 a 5 salários mínimos), `3` (De 5 a 10 salários mínimos), `4` (De 10 a 20 salários mínimos), `5` (Mais de 20 salários mínimos) ou `99` (Sem informação)                                                                                     |

No retorno de sucesso, os dados do cartão, seja novo ou pré-existente são retornados.

_Códigos de erro:_

- `400`: para erros na requisição, como de sintaxe, campo faltante ou inválido,
  nesses casos, pode ser retornado uma lista dos erros encontrados.
- `401`: para erros relativos à autenticação ou à autorização.

+ Request Adesão (application/json)
    + Headers

            Authorization: Bearer <TOKEN>

    + Attributes (Client)

+ Response 201 (application/json)

    + Attributes (object)
        + status: `201` (number) - O mesmo código de resposta do HTTP
        + defaultMessage: `Adesão on-line` (string) - Descrição da resposta
        + body (object)
            + message: `Carga de cliente finalizada com sucesso` (string)
            + card (Card) - Informações do cartão ativada
            + errors (array) - Lista de erros

## Atualiza Status do Cartão [/api/sempre/cards/update]

### POST

Faz a atualização de status de um cartão de saúde.

A entrada deve ser um JSON com os seguintes campos:

| Campos              | Tipo   | Obrigatório | Descrição                                                                                               |
| ------------------- | ------ | :---------: | ------------------------------------------------------------------------------------------------------- |
| `cardNumber`        | String | Sim         | Número do cartão de saúde.                                                                              |
| `status`            | String | Sim         | O novo status para o cartão: `HABILITADO`, `SUSPENSO` ou `CANCELADO`.                                   |
| `historyType`       | String | Sim         | O tipo de histórico da alteração do cartão: `HABILITACAO`, `SUSPENSAO`, `REATIVACAO` ou `CANCELAMENTO`. |
| `reasonDescription` | String | Não         | Um texto qualquer para explicar o motivo da alteração de cartão.                                        |

No retorno de sucesso, o status anterior e o novo são retornados.

_Códigos de erro:_

- `400`: para erros na requisição, como de sintaxe, campo faltante ou inválido,
  nesses casos, pode ser retornado uma lista dos erros encontrados.
- `401`: para erros relativos à autenticação ou à autorização.

+ Request Adesão (application/json)
    + Headers

            Authorization: Bearer <TOKEN>

    + Body
    
            {
                "cardNumber": "6064070028552319", 
                "status": "HABILITADO",
                "historyType": "SUSPENSAO",
                "reasonDescription": null
            }

+ Response 202 (application/json)

        {
            "status": 202,
            "defaultMessage": "Altera o status do cartão de saúde",
            "body": {
                "cardNumber": "6064070028552319",
                "oldStatus": "SUSPENSO",
                "newStatus": "HABILITADO",
                "changed": true
            }
        }

# Group Autorização

## Token [/api/sempre/oauth/token]

### POST

Obtém um token temporário para ser usado na API, esse token deve ser reutilizado até expirar.

Utiliza o modo de autenticação _HTTP Basic_, seguindo o modo `client_credentials`.

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization: Basic <CREDENTIALS>
    
    + Body

            grant_type=client_credentials

+ Response 200 (application/json)

        {
            "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
            "token_type": "bearer",
            "expires_in": 29999999,
            "scope": "all",
            "jti": "ab6abdb1-4d08-4a9c-9d49-3fdcb1a81611"
        }

+ Response 401 (application/json)

        {
            "status": 401,
            "timestamp": "2018-06-28",
            "error": "Unauthorized",
            "message": "Unauthorized",
            "path": "/api/sempre/oauth/token"
        }

# Data Structures

## Client (object)

+ currentUser: `<USUÁRIO>` (string, required) - Identificação de quem fez a operação
+ action: `1` (number, required) - Ação a ser efetuada: 1 (Adesão) e 4 (Suspensão)
+ cardNumber: `1234567654321234` (string) - Número do cartão de saúde (obrigatório em alguns produtos)
+ majorCard: `null` (string) - Número do cartão pai
+ onixCode: `<ONIX_CODE>` (string, required) - Código do produto usado no cartão de saúde
+ cpfOrCnpj: `28937645173` (string, required) - Número de CPF do cliente
+ name: `Maria Vitória Cunha` (string, required) - Nome completo do cliente
+ shortName: `M. V. Cunha` (string) - Nome abreviado (usado no cartão)
+ birthdate: `1991-11-12` (string, required) - Data de nascimento do cliente
+ telephone: `81996762941` (string, required) - Número de celular do cliente com DDD
+ externalIdentifier: null (string) - Identificador externo usado para identificar o cartão e/ou cliente no sistema externo do parceiro.
+ email: `maria@exemplo.com` (string) - Um e-mail válido para contato com o cliente
+ gender: `F` (string, required) - Gênero do cliente (M/F)
+ address: `Rua Teófilo Prado` (string) - Endereço do cliente (logradouro)
+ number: `561` (string) - Endereço do cliente (número)
+ complement: `Ap. 1102` (string) - Endereço do cliente (complemento)
+ neighborhood: `Jardins` (string) - Endereço do cliente (bairro)
+ city: `Campinas` (string) - Endereço do cliente (cidade)
+ state: `SP` (string) - Endereço do cliente (UF)
+ postalCode: `01310100` (string) - Endereço do cliente (CEP) - somente números
+ rg: `100345` (string) - Número do documento do cliente
+ documentType: `1` (number) - Tipo de documento: 1 (RG), 2 (PASSAPORTE), 3 (CTPS) ou 4 (CNH)
+ nationality: `Brasileira` (string) - Naturalidade do cliente.
+ race: 99 (number) - Etnia do cliente: 1 (Branca), 2 (Negra), 3 (Parda), 4 (Amarela), 5 (Indígena) ou 99 (sem informação)
+ scholarity: 99 (number) - Escolaridade do cliente: 1 (Analfabeto), 2 (Alfabetizado), 3 (1o Grau Incompleto), 4 (1o Grau Completo), 5 (2o Grau Incompleto) 6 (2o Grau Completo), 7 (Superior Incompleto), 8 (Superior Completo), 9 (Especialização), 10 (Mestrado), 11 (Doutorado) ou 99 (sem informação)
+ incomeClass: 99 (number) - Classe de rendimento: 1 (Até 1 salário mínimo), 2 (De 2 a 5 salários mínimos), 3 (De 5 a 10 salários mínimos), 4 (De 10 a 20 salários mínimos), 5 (Mais de 20 salários mínimos) ou 99 (Sem informação)

## Card (object)

+ cardNumber: `1234567654321234` (string) - Número do cartão para o cliente
+ cvv: `321` (string) - Código de segurança do cartão
+ way: `1` (string) - Número da via
+ password: `874125` (string) - Senha inicial do cliente
+ emitter: `755` (string) - Código do emissor
+ product: `<ONIX_CODE>` (string) - Código do produto