FORMAT: 1A

# API Agendamento

API REST para agendamento de consultas e exames em prestadores conveniados à Rede TEM.

## URL

A URL base depende do ambiente:

<dl>
<dt>Homologação</dt>
<dd>https://qa-api.meutem.com.br</dd>
<dt>Produção</dt>
<dd>https://api.meutem.com.br</dd>
</dl>

> O endereço de produção só funciona para IP previamente liberado.

## Autenticação

Essa API exige em toda requisição o envio de uma chave de transação nos cabeçalhos,
o valor da chave a ser usada deve ser solicitada previamente.

```
Transaction-Key: <KEY>
```

# Group Agendamento

## Agendamento de Consultas [/app/tickets/appointment]

### POST

Realiza o agendamento de consulta em um prestador conveniado à Rede TEM.

#### Sobre a requisição

A entrada deve ser um JSON com os seguintes campos:

| Atributo               | Tipo   | Obrigatório | Descrição                                                                                              |
| ---------------------- | ------ | :---------: | ------------------------------------------------------------------------------------------------------ |
| `cpf`                  | String | Sim         | Número de CPF do cliente (somente números).                                                            |
| `card_number`          | String | Sim         | Número de cartão do cliente (somente números).                                                         |
| `specialty`            | String | Sim         | Nome da especialidade como está descrita na resposta da consulta de especialidades da API de SAC.      |
| `best_hour`            | String | Sim         | Melhor horário para a consulta: pode ser `m` (Manhã), `t` (Tarde), `n` (Noite), `q` (Qualquer Período) |
| `best_days`            | Array  | Sim         | Melhores dias da semana para a consulta: `Segunda`, `Terça`, `Quarta`, `Quinta`, `Sexta`               |
| `state`                | String | Não         | O estado para onde a consulta deve ser agendada. Use a sigla da UF.                                    |
| `city`                 | String | Não         | O nome da cidade para onde a consulta deve ser agendada.                                               |
| `zone`                 | String | Não         | A região para onde a consulta deve ser agendada.                                                       |
| `patient_name`         | String | Não[\*]()   | Nome completo do paciente.                                                                             |
| `patient_relationship` | String | Não[\*]()   | Parentesco do paciente com o cliente: deve ser `CO` (cônjuge) ou `FI` (filho ou filha)                 |
| `patient_birthdate`    | String | Não[\*]()   | Data de nascimento do paciente no formato `yyyy-MM-dd`.                                                |
| `description`          | String | Não         | Qualquer informação adicional sobre o agendamento.                                                     |

[\*]() Os dados do paciente só devem ser informados quando o agendamemnto for para um depedente do cliente.

#### Sobre a resposta

Na resposta de sucesso, é retornado outro JSON:

| Campo       | Tipo   | Descrição                           |
| ----------- | ------ | ----------------------------------- |
| `status`    | String | O mesmo código de resposta do HTTP. |
| `message`   | String | Descrição da resposta.              |
| `ticket_id` | String | O número do ticket.                 |

#### Códigos de erro

| Código | Descrição                                                              |
| ------ | ---------------------------------------------------------------------- |
| `400`  | Para erros na requisição, como de sintaxe, campo faltante ou inválido. |
| `401`  | Para erros relativos à autorização.                                    |
| `404`  | Se o cliente de CPF e Número da Cartão passado não foi encontrado.     |
| `500`  | Para erros indeterminados.                                             |

+ Request (application/json)
    + Headers

            Transaction-Key: <KEY>

    + Attributes (Appointment)

+ Response 201 (application/json)

    + Attributes (Ticket)

## Agendamento de Exames [/app/tickets/exam]

### POST

Realiza o agendamento de exame em um prestador conveniado à Rede TEM.

#### Sobre a requisição

A entrada deve ser um JSON com os seguintes campos:

| Atributo               | Tipo   | Obrigatório | Descrição                                                                                                                                                                             |
| ---------------------- | ------ | :---------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `cpf`                  | String | Sim         | Número de CPF do cliente (somente números).                                                                                                                                           |
| `card_number`          | String | Sim         | Número de cartão do cliente (somente números).                                                                                                                                        |
| `exam_group`           | String | Sim         | Grupo de exames: deve ser `AC` (Análises Clínicas), `EC` (Exames/Cardialógicos), `EG` (Exames/Ginecológicos), `EI` (Exames/Imagem), `EP` (Exames/Patológico) ou `NI` (Não Informado). |
| `best_hour`            | String | Sim         | Melhor horário para o exame: pode ser `m` (Manhã), `t` (Tarde), `n` (Noite), `q` (Qualquer Período)                                                                                   |
| `best_days`            | Array  | Sim         | Melhores dias da semana para o exame: `Segunda`, `Terça`, `Quarta`, `Quinta`, `Sexta`                                                                                                 |
| `state`                | String | Não         | O estado para onde o exame deve ser agendada. Use a sigla da UF.                                                                                                                      |
| `city`                 | String | Não         | O nome da cidade para onde o exame deve ser agendada.                                                                                                                                 |
| `zone`                 | String | Não         | A região para onde o exame deve ser agendada.                                                                                                                                         |
| `patient_name`         | String | Não[\*](#p) | Nome completo do paciente.                                                                                                                                                            |
| `patient_relationship` | String | Não[\*](#p) | Parentesco do paciente com o cliente: deve ser `CO` (cônjuge) ou `FI` (filho ou filha)                                                                                                |
| `patient_birthdate`    | String | Não[\*](#p) | Data de nascimento do paciente no formato `yyyy-MM-dd`.                                                                                                                               |
| `description`          | String | Não         | Qualquer informação adicional sobre o agendamento.                                                                                                                                    |
| `attachment`           | Binary | Sim[\*\*]() | Uma foto da solicitação de exame assinada pelo médico.                                                                                                                                |

[\*]() Os dados do paciente só devem ser informados quando o agendamemnto for para um depedente do cliente.
[\*\*]() O anexo só poderá ser enviado com o formato `multipart/form-data` em vez de JSON.

#### Sobre a resposta

Na resposta de sucesso, é retornado outro JSON:

| Campo       | Tipo   | Descrição                           |
| ----------- | ------ | ----------------------------------- |
| `status`    | String | O mesmo código de resposta do HTTP. |
| `message`   | String | Descrição da resposta.              |
| `ticket_id` | String | O número do ticket.                 |

#### Códigos de erro

| Código | Descrição                                                              |
| ------ | ---------------------------------------------------------------------- |
| `400`  | Para erros na requisição, como de sintaxe, campo faltante ou inválido. |
| `401`  | Para erros relativos à autorização.                                    |
| `404`  | Se o cliente de CPF e Número da Cartão passado não foi encontrado.     |
| `500`  | Para erros indeterminados.                                             |

+ Request (multipart/form-data; boundary=AzB03x567)
    + Headers

            Transaction-Key: <KEY>

    + Body

            --AzB03x567
            Content-Disposition: form-data; name="attachment"; filename="exam-client.png"
            Content-Type: image/png

            <DADOS BINÁRIOS>
            --AzB03x567
            Content-Disposition: form-data; name="cpf"

            05910470558
            --AzB03x567
            Content-Disposition: form-data; name="card_number"

            6064070024962610
            --AzB03x567
            Content-Disposition: form-data; name="exam_group"

            AC
            --AzB03x567
            Content-Disposition: form-data; name="best_hour"

            m
            --AzB03x567
            Content-Disposition: form-data; name="best_days"

            ["Segunda", "Terça"]
            --AzB03x567
            Content-Disposition: form-data; name="state"

            SE
            --AzB03x567
            Content-Disposition: form-data; name="city"

            Aracaju
            --AzB03x567

+ Response 201 (application/json)

    + Attributes (Ticket)

# Data Structures

## Appointment (object)
+ cpf: `05910470558` (string, required) - Número de CPF do cliente (somente números).
+ card_number: `6064070152759819` (string, required) - Número de cartão do cliente (somente números).
+ specialty: `ALERGIA E IMUNOLOGIA` (string, required) - Nome da especialidade como está descrita na resposta da consulta de especialidades da API de SAC.
+ best_hour: `m` (string, required) - Melhor horário para a consulta: pode ser 'm' (Manhã), 't' (Tarde), 'n' (Noite), 'q' (Qualquer Período)
+ best_days: `Segunda`, `Terça` (array[string], required) - Melhores dias da semana para a consulta: Segunda, Terça, Quarta, Quinta, Sexta
+ state: `SE` (string) - O estado para onde a consulta deve ser agendada. Use a sigla da UF.
+ city: `Aracaju` (string) - O nome da cidade para onde a consulta deve ser agendada.
+ zone: `SP - Zona Leste` (string) - A região para onde a consulta deve ser agendada.
+ patient_name: `Renata de Albuquerque Souza` (string) - Nome completo do paciente.
+ patient_relationship: `FI` (string) - Parentesco do paciente com o cliente: deve ser CO (cônjuge) ou FI (filho ou filha)
+ patient_birthdate: `1995-05-11` (string) - Data de nascimento do paciente.
+ description: `Gostaria que o profissional fosse mulher` (string) - Observação feita pelo cliente no momento do agendamento.

## Exam
+ cpf: `05910470558` (string, required) - Número de CPF do cliente (somente números).
+ card_number: `6064070152759819` (string, required) - Número de cartão do cliente (somente números).
+ exam_group: `AC` (string, required) - Grupo de exames: deve ser AC (Análises Clínicas), EC (Exames/Cardialógicos), EG (Exames/Ginecológicos), EI (Exames/Imagem), EP (Exames/Patológico) ou NI (Não Informado).
+ best_hour: `m` (string, required) - Melhor horário para o exame: pode ser 'm' (Manhã), 't' (Tarde), 'n' (Noite), 'q' (Qualquer Período)
+ best_days: `Segunda`, `Terça` (array[string], required) - Melhores dias da semana para o exame: Segunda, Terça, Quarta, Quinta, Sexta
+ state: `SE` (string) - O estado para onde a consulta deve ser agendada. Use a sigla da UF.
+ city: `Aracaju` (string) - O nome da cidade para onde a consulta deve ser agendada.
+ zone: `SP - Zona Leste` (string) - A região para onde a consulta deve ser agendada.
+ patient_name: `Renata de Albuquerque Souza` (string) - Nome completo do paciente.
+ patient_relationship: `FI` (string) - Parentesco do paciente com o cliente: deve ser CO (cônjuge) ou FI (filho ou filha)
+ patient_birthdate: `1995-05-11` (string) - Data de nascimento do paciente.
+ description: `Gostaria que o profissional fosse homem` (string) - Observação feita pelo cliente no momento do agendamento.
+ attachment - Uma foto da solicitação de exame assinada pelo médico.

## Ticket
+ status: `201` (number) - O mesmo código de resposta do HTTP.
+ message: `Agendamento realizado com sucesso.` (string) - Descrição da resposta.
+ ticket_id: `34209` (number) - O número do ticket.
