FORMAT: 1A

# API TEM

<div style="font-size: 1.25em">

Documentações fornecidas pela Rede TEM:

- [API SAC](sac.html)
- [API Agendamento](ticket.html)
- [API Farmácias](drugstore.html)
- [API Prestadores](provider.html)
- [API Sempre](sempre.html)
- [API Faturamento](billing.html)

</div>
